[package]
name = "todo_rs"
version = "0.1.0"
authors = ["Ken Cruz <ken@kencruz.ca>"]
edition = "2018"

[dependencies]
actix-web = "1.0.5"
actix-files = "0.1.4"
diesel = { version = "1.4.2", features = ["sqlite", "r2d2"] }
serde = { version = "1.0.99", features = ["derive"] }
futures = "0.1.28"
